services:
  - type: web
    name: onlineshop-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run start:prod
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ISSUER
        value: OnlineShopBackend
      - key: JWT_AUDIENCE
        value: OnlineShopFrontend
      - key: JWT_EXPIRES_IN_MINUTES
        value: "60"
      - key: DB_SQLITE_PATH
        value: shop.db
      - key: EmailSettings__SmtpHost
        sync: false
      - key: EmailSettings__SmtpPort
        sync: false
      - key: EmailSettings__EnableSsl
        sync: false
      - key: EmailSettings__UserName
        sync: false
      - key: EmailSettings__Password
        sync: false
      - key: EmailSettings__FromEmail
        sync: false
      - key: EmailSettings__NotifyEmail
        sync: false
